apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-eks-jenkins 
  labels:
    app: testwebapp
spec:
  selector:
    matchLabels:
        app: testwebapp
  replicas: 2
  template:
    metadata:
      labels:
        app: testwebapp
    spec:
      containers:
        - name: testwebapp
          image: index.docker.io/gvkr1409/testwebapp:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
